----------------------------------------------------------------------
-- My Ipe customizations: customization.lua
----------------------------------------------------------------------
-- prefs.latex_service_url = "http://latexonline.cc"
