; Global settings for redshift
[redshift]
; Set the day and night screen temperatures
temp-day=6500
temp-night=1200

; Time interval for the temperature transition
dawn-time=6:00-6:01
dusk-time=21:00-21:01
